In [2]:
import pandas as pd

arquivo = "base/base_cafe.xlsx"

mambo = pd.read_excel(arquivo, sheet_name="mambo")
marche = pd.read_excel(arquivo, sheet_name="marche")

mambo.head()

,SKU,Titulo,Fabricante,Tipo Produto,Departamento,Categoria,Sub Categoria,GTIN,Modelo,Bytes,...,_3,_4,_5,_6,_7,_8,_9,_10,_11,CLUSTER PAO
0,2532,Café Torrado e Moído Superior Aviação 500g,Aviação,NaN,Mambo,Mercearia,NaN,7896331100648,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2533,Café Torrado e Moído 252 Graus a Vácuo Pilão 500g,Pilão,NaN,Mambo,Mercearia,NaN,7896089013849,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2534,Café Torrado e Moído 252° Graus Abre & Fecha P...,Pilão,NaN,Mambo,Mercearia,NaN,7896089013856,NaN,NaN,...,https://mambodelivery.vteximg.com.br/arquivos/...,https://mambodelivery.vteximg.com.br/arquivos/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7641688.0
3,2536,Café Torrado e Moído a Vácuo Tradicional 3 Cor...,3 Corações,NaN,Mambo,Mercearia,NaN,7896045102440,NaN,NaN,...,https://mambodelivery.vteximg.com.br/arquivos/...,https://mambodelivery.vteximg.com.br/arquivos/...,https://mambodelivery.vteximg.com.br/arquivos/...,https://mambodelivery.vteximg.com.br/arquivos/...,https://mambodelivery.vteximg.com.br/arquivos/...,https://mambodelivery.vteximg.com.br/arquivos/...,NaN,NaN,NaN,NaN
4,2537,Cápsula de Café Aqtivus 8 Delta 55g com 10 Uni...,Delta Q,NaN,Mambo,Mercearia,NaN,5601082038537,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
mambo.columns

Index(['SKU', 'Titulo', 'Fabricante', 'Tipo Produto', 'Departamento',
       'Categoria', 'Sub Categoria', 'GTIN', 'Modelo', 'Bytes', 'Litros',
       'Tamanho', 'Qtde. Pacote', 'Cor', 'Peso', 'Genero', 'Volume',
       'Voltagem', 'Disponibilidade', 'Preco', 'Preço Oferta', 'Vendedor',
       'Descricao', 'Descricao_1', 'URL', 'URL Imagem', 'URL Imagem_2',
       'Column1', '_3', '_4', '_5', '_6', '_7', '_8', '_9', '_10', '_11',
       'CLUSTER PAO'],
      dtype='str')

In [4]:
colunas_importantes_mambo = [
    "SKU",
    "Titulo",
    "Fabricante",
    "Categoria",
    "Disponibilidade",
    "Preco",
    "Preço Oferta",
    "URL"
]

mambo = mambo[colunas_importantes_mambo]

mambo.head(50)

,SKU,Titulo,Fabricante,Categoria,Disponibilidade,Preco,Preço Oferta,URL
0,2532,Café Torrado e Moído Superior Aviação 500g,Aviação,Mercearia,Disponivel,54.98,54.98,https://www.mambo.com.br/cafe-superior-moido-a...
1,2533,Café Torrado e Moído 252 Graus a Vácuo Pilão 500g,Pilão,Mercearia,Disponivel,43.49,43.49,https://www.mambo.com.br/cafe-torrado-e-moido-...
2,2534,Café Torrado e Moído 252° Graus Abre & Fecha P...,Pilão,Mercearia,Disponivel,43.49,43.49,https://www.mambo.com.br/cafe-torrado-e-moido-...
3,2536,Café Torrado e Moído a Vácuo Tradicional 3 Cor...,3 Corações,Mercearia,Disponivel,27.99,27.99,https://www.mambo.com.br/cafe-torrado-e-moido-...
4,2537,Cápsula de Café Aqtivus 8 Delta 55g com 10 Uni...,Delta Q,Mercearia,Disponivel,28.49,28.49,https://www.mambo.com.br/cafe-aqtivus-8-delta-...
5,2538,Café Torrado e Moído Aromatizado Amêndoas Torr...,Floresta,Mercearia,Disponivel,19.98,19.98,https://www.mambo.com.br/cafe-aromatizado-amen...
6,2539,Café Torrado e Moído Aromatizado Baunilha com ...,Floresta,Mercearia,Disponivel,19.98,19.98,https://www.mambo.com.br/cafe-aromatizado-baun...
7,2541,Café Torrado e Moído Aromatizado Crème Brulée ...,Floresta,Mercearia,Disponivel,19.98,19.98,https://www.mambo.com.br/cafe-aromatizado-crem...
8,2542,Café Torrado e Moído Aromatizado Trufas com Ch...,Floresta,Mercearia,Disponivel,19.98,19.98,https://www.mambo.com.br/cafe-aromatizado-truf...
9,2543,Cápsula de Café Barítono Bravo 50g com 10 Unid...,Bravo Café,Mercearia,Disponivel,23.98,23.98,https://www.mambo.com.br/cafe-baritono-bravo-5...
10,2545,Cápsula de Café Blonde Espresso Roast Starbuck...,Nescafé,Mercearia,Disponivel,32.98,32.98,https://www.mambo.com.br/cafe-blonde-espresso-...
11,2545,Cápsula de Café Blonde Espresso Roast Starbuck...,Nescafé,Mercearia,Disponivel,32.98,32.98,https://www.mambo.com.br/cafe-blonde-espresso-...
12,2546,Café Torrado e Moído Bourbon Amarelo Varietais...,Orfeu,Mercearia,Disponivel,42.49,42.49,https://www.mambo.com.br/cafe-torrado-e-moido-...
13,2547,Cápsula de Café Bourbon Amarelo Orfeu 50g com ...,Orfeu,Mercearia,Disponivel,26.99,26.99,https://www.mambo.com.br/cafe-bourbon-amarelo-...
14,2555,Cápsula de Café Clássico Orfeu 50g com 10 Unid...,Orfeu,Mercearia,Disponivel,26.99,26.99,https://www.mambo.com.br/cafe-classico-orfeu-5...
15,2556,Cápsula de Café Single-Origin Colombia Nespres...,Nescafé,Mercearia,Disponivel,32.98,32.98,https://www.mambo.com.br/capsula-de-cafe-singl...
16,2557,Cápsula de Café com Cacau Italle 25g com 10 Un...,Italle,Mercearia,Disponivel,18.99,18.99,https://www.mambo.com.br/cafe-com-cacau-italle...
17,2559,Cápsula de Café Com Leite Tres 3 Corações 90g ...,3 Corações,Mercearia,Disponivel,17.98,17.98,https://www.mambo.com.br/capsula-de-cafe-com-l...
18,2561,Cápsula de Café Baileys Supremo Macchiato Tres...,3 Corações,Mercearia,Disponivel,17.98,17.98,https://www.mambo.com.br/capsula-baileys-supre...
19,2568,Cápsula de Café Espresso Forza Tres 3 Corações...,3 Corações,Mercearia,Disponivel,17.98,17.98,https://www.mambo.com.br/capsula-de-cafe-espre...
20,2572,Café Torrado e Moído Descafeinado a Vácuo 3 Co...,3 Corações,Mercearia,Disponivel,40.98,40.98,https://www.mambo.com.br/cafe-torrado-e-moido-...
21,2573,Café Torrado e Moído Descafeinado Melitta 250g,Melitta,Mercearia,Disponivel,40.98,40.98,https://www.mambo.com.br/cafe-torrado-e-moido-...
22,2575,Café Torrado e Moído Descafeínado a Vácuo Pilã...,Pilão,Mercearia,Disponivel,40.98,40.98,https://www.mambo.com.br/cafe-torrado-e-moido-...
23,2577,Cápsula de Café Orgânico Santa Mônica 50g com ...,Santa Mônica,Mercearia,Indisponivel,0.00,0.00,https://www.mambo.com.br/capsula-de-cafe-organ...
24,2578,Cápsula de Café Bourbon Amarelo Orfeu 50g com ...,Orfeu,Mercearia,Disponivel,29.99,29.99,https://www.mambo.com.br/capsula-de-cafe-bourb...
25,2579,Cápsula de Café Clássico Orfeu 90g com 10 Unid...,Orfeu,Mercearia,Disponivel,29.99,29.99,https://www.mambo.com.br/capsula-de-cafe-class...
26,2582,Cápsula de Café Intenso Orfeu 90g com 10 Unidades,Orfeu,Mercearia,Disponivel,29.99,29.99,https://www.mambo.com.br/capsula-de-cafe-inten...
27,2583,Cápsula de Café Orgânico Orfeu 90g com 10 Unid...,Orfeu,Mercearia,Disponivel,36.98,36.98,https://www.mambo.com.br/capsula-de-cafe-organ...
28,2585,Cápsula de Café Torrado e Moído Clássico Espre...,Illy,Mercearia,Disponivel,24.99,24.99,https://www.mambo.com.br/capsula-de-cafe-torra...
29,2587,Cápsula de Café Forte Espresso Illy Caixa 57g ...,Illy,Mercearia,Disponivel,24.99,24.99,https://www.mambo.com.br/capsula-de-cafe-forte...
30,2589,Cápsula de Café Intenso Espresso Illy Caixa 57...,Illy,Mercearia,Disponivel,24.99,24.99,https://www.mambo.com.br/capsula-de-cafe-inten...
31,2595,Café em Grãos Classico Illy Blend 250g,Illy,Mercearia,Disponivel,48.98,48.98,https://www.mambo.com.br/cafe-em-graos-torra-m...
32,2596,Cápsula de Café Epiq Intensidade 14 Delta Q 55...,Delta Q,Mercearia,Disponivel,28.49,28.49,https://www.mambo.com.br/cafe-epiq-intensidade...
33,2597,Café Torrado e Moído Especial a Vácuo Melitta ...,Melitta,Mercearia,Disponivel,56.98,56.98,https://www.mambo.com.br/cafe-torrado-e-moido-...
34,2598,Café em Cápsulas de Torrado e moído Pilão Fort...,Pilão,Mercearia,Disponivel,25.49,25.49,https://www.mambo.com.br/cafe-em-capsulas-de-t...
35,2599,Café em Cápsula Torrado e Moído Espresso Extra...,Pilão,Mercearia,Disponivel,25.49,25.49,https://www.mambo.com.br/cafe-em-capsula-torra...
36,2600,Café em Cápsulas de Torrado e moído Pilão Trad...,Pilão,Mercearia,Disponivel,25.49,25.49,https://www.mambo.com.br/capsula-de-cafe-espre...
37,2601,Cápsula de Café Espresso Ameno Tres 3 Corações...,3 Corações,Mercearia,Disponivel,17.98,17.98,https://www.mambo.com.br/capsula-de-cafe-espre...
38,2602,Cápsula de Café Espresso Atento Tres 3 Coraçõe...,3 Corações,Mercearia,Disponivel,17.98,17.98,https://www.mambo.com.br/capsula-de-cafe-espre...
39,2604,Cápsula de Café Espresso Colombia L'or 52g com...,Lor,Mercearia,Disponivel,30.98,30.98,https://www.mambo.com.br/cafe-espresso-colombi...
40,2605,Cápsula de Café Descafeinado Tres 3 Corações 8...,3 Corações,Mercearia,Disponivel,17.98,17.98,https://www.mambo.com.br/capsula-de-cafe-desca...
41,2606,Cápsula de Café Espresso Forza L'or 52 com 10 ...,Lor,Mercearia,Disponivel,30.98,30.98,https://www.mambo.com.br/cafe-espresso-forza-l...
42,2607,Café em Grãos Espresso Gourmet Ituano 1kg,Ituano,Mercearia,Disponivel,119.98,119.98,https://www.mambo.com.br/cafe-em-graos-espress...
43,2608,Café em Grãos Espresso Intenso Evolutto 1kg,Evolutto,Mercearia,Disponivel,132.98,132.98,https://www.mambo.com.br/cafe-em-graos-espress...
44,2609,Cápsula de Café Espresso Lungo Estremo L'or 52...,Lor,Mercearia,Disponivel,30.98,30.98,https://www.mambo.com.br/cafe-espresso-lungo-e...
45,2611,Cápsula de Café Espresso Onyx L'or 52g com 10 ...,Lor,Mercearia,Disponivel,30.98,30.98,https://www.mambo.com.br/cafe-espresso-onyx-lo...
46,2612,Cápsula de Café Espresso PapuaCafé Espresso Pa...,Lor,Mercearia,Indisponivel,0.00,0.00,https://www.mambo.com.br/cafe-espresso-papuaca...
47,2613,Cápsula de Café Espresso Pleno Tres 3 Corações...,3 Corações,Mercearia,Disponivel,17.98,17.98,https://www.mambo.com.br/capsula-de-cafe-espre...
48,2614,Cápsula de Café Espresso Ristretto Descafeinad...,Lor,Mercearia,Disponivel,30.98,30.98,https://www.mambo.com.br/cafe-espresso-ristret...
49,2616,Cápsula de Café Espresso Ristretto L'or 52g co...,Lor,Mercearia,Disponivel,30.98,30.98,https://www.mambo.com.br/cafe-espresso-ristret...

In [5]:
mambo.info()

<class 'pandas.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   SKU              498 non-null    int64
 1   Titulo           498 non-null    str
 2   Fabricante       498 non-null    str
 3   Categoria        498 non-null    str
 4   Disponibilidade  498 non-null    str
 5   Preco            498 non-null    float64
 6   Preço Oferta     498 non-null    float64
 7   URL              498 non-null    str
dtypes: float64(2), int64(1), str(5)
memory usage: 31.3 KB

In [6]:
mambo["Fabricante"].unique()

<StringArray>
[        'Aviação',           'Pilão',      '3 Corações',         'Delta Q',
        'Floresta',      'Bravo Café',         'Nescafé',           'Orfeu',
          'Italle',         'Melitta',    'Santa Mônica',            'Illy',
             'Lor',          'Ituano',        'Evolutto',          'Native',
   'Cafe Floresta',       'Café Pelé',     'Café Toledo',          'Baggio',
    'Cia Organica',       'Starbucks',          'Iguaçu',          'Nestlé',
     'Cafe Iguacu',   'Prima Qualita',   'Café do Ponto',         'Caboclo',
         'Havanna',           'União',           'Camil',            'Fort',
 'Café Brasileiro',      'Brasileiro',   'Caffè Corsini',       'Coffee ++',
         'Lavazza',     'Juan Valdez',    'Santa Monica',         'Carraro',
        'Bialetti',       'Luvizotto',          'Gaggia',        'Bauducco',
            'Gold',           'Bravo']
Length: 46, dtype: str

In [7]:
mambo["Fabricante"].value_counts()

Fabricante
3 Corações         92
Nescafé            70
Lor                39
Orfeu              33
Pilão              31
Coffee ++          29
Melitta            25
Baggio             19
Illy               15
Bravo Café         10
Santa Mônica       10
Italle              9
União               9
Caffè Corsini       9
Starbucks           8
Nestlé              7
Juan Valdez         7
Delta Q             6
Café Brasileiro     6
Carraro             5
Floresta            4
Café Toledo         4
Cia Organica        4
Iguaçu              4
Lavazza             4
Santa Monica        4
Ituano              3
Native              3
Café do Ponto       3
Luvizotto           3
Gold                3
Aviação             2
Evolutto            2
Cafe Floresta       2
Prima Qualita       2
Bialetti            2
Café Pelé           1
Cafe Iguacu         1
Caboclo             1
Havanna             1
Camil               1
Fort                1
Brasileiro          1
Gaggia              1
Bauducco            1
Bravo               1
Name: count, dtype: int64

In [8]:
mambo["Preco"] = pd.to_numeric(mambo["Preco"], errors="coerce")
mambo["Preço Oferta"] = pd.to_numeric(mambo["Preço Oferta"], errors="coerce")

In [9]:
mambo["Disponibilidade"].value_counts()

Disponibilidade
Disponivel      456
Indisponivel     42
Name: count, dtype: int64

In [10]:
mambo = mambo[mambo["Disponibilidade"] == "Disponivel"] 
mambo.head()

,SKU,Titulo,Fabricante,Categoria,Disponibilidade,Preco,Preço Oferta,URL
0,2532,Café Torrado e Moído Superior Aviação 500g,Aviação,Mercearia,Disponivel,54.98,54.98,https://www.mambo.com.br/cafe-superior-moido-a...
1,2533,Café Torrado e Moído 252 Graus a Vácuo Pilão 500g,Pilão,Mercearia,Disponivel,43.49,43.49,https://www.mambo.com.br/cafe-torrado-e-moido-...
2,2534,Café Torrado e Moído 252° Graus Abre & Fecha P...,Pilão,Mercearia,Disponivel,43.49,43.49,https://www.mambo.com.br/cafe-torrado-e-moido-...
3,2536,Café Torrado e Moído a Vácuo Tradicional 3 Cor...,3 Corações,Mercearia,Disponivel,27.99,27.99,https://www.mambo.com.br/cafe-torrado-e-moido-...
4,2537,Cápsula de Café Aqtivus 8 Delta 55g com 10 Uni...,Delta Q,Mercearia,Disponivel,28.49,28.49,https://www.mambo.com.br/cafe-aqtivus-8-delta-...

In [11]:
mambo.shape

(456, 8)

In [12]:
mambo["Preco"].mean()

np.float64(34.09763157894737)

In [13]:
mambo.groupby("Fabricante")["Preco"].mean().sort_values()

Fabricante
Italle              15.878889
Havanna             17.980000
Floresta            19.980000
União               20.646667
Iguaçu              20.840000
Bauducco            21.900000
3 Corações          24.434588
Carraro             24.980000
Gold                25.320000
Camil               25.900000
Nescafé             25.949107
Café Brasileiro     27.490000
Cafe Iguacu         27.990000
Bravo Café          28.222222
Delta Q             28.490000
Melitta             28.840833
Brasileiro          28.990000
Fort                28.990000
Lor                 29.453056
Native              29.980000
Nestlé              30.871667
Cafe Floresta       34.980000
Caboclo             35.980000
Coffee ++           36.903793
Café Pelé           36.980000
Baggio              37.511667
Illy                39.050667
Pilão               39.503000
Orfeu               39.909697
Santa Mônica        41.898333
Café Toledo         46.740000
Cia Organica        49.107500
Bialetti            49.235000
Starbucks           53.338571
Caffè Corsini       53.930000
Aviação             54.980000
Café do Ponto       55.980000
Santa Monica        70.735000
Juan Valdez         77.982857
Evolutto            84.980000
Prima Qualita       85.980000
Ituano              87.980000
Luvizotto          110.150000
Name: Preco, dtype: float64

In [14]:
mambo.groupby("Fabricante")["Preco"].mean().sort_values(ascending=False)

Fabricante
Luvizotto          110.150000
Ituano              87.980000
Prima Qualita       85.980000
Evolutto            84.980000
Juan Valdez         77.982857
Santa Monica        70.735000
Café do Ponto       55.980000
Aviação             54.980000
Caffè Corsini       53.930000
Starbucks           53.338571
Bialetti            49.235000
Cia Organica        49.107500
Café Toledo         46.740000
Santa Mônica        41.898333
Orfeu               39.909697
Pilão               39.503000
Illy                39.050667
Baggio              37.511667
Café Pelé           36.980000
Coffee ++           36.903793
Caboclo             35.980000
Cafe Floresta       34.980000
Nestlé              30.871667
Native              29.980000
Lor                 29.453056
Brasileiro          28.990000
Fort                28.990000
Melitta             28.840833
Delta Q             28.490000
Bravo Café          28.222222
Cafe Iguacu         27.990000
Café Brasileiro     27.490000
Nescafé             25.949107
Camil               25.900000
Gold                25.320000
Carraro             24.980000
3 Corações          24.434588
Bauducco            21.900000
Iguaçu              20.840000
União               20.646667
Floresta            19.980000
Havanna             17.980000
Italle              15.878889
Name: Preco, dtype: float64

In [15]:
mambo.to_csv("mambo.csv", index=False)

In [16]:
mambo[mambo["Fabricante"] == "União"].value_counts()

SKU     Titulo                                                            Fabricante  Categoria  Disponibilidade  Preco  Preço Oferta  URL
16411   Café Torrado e Moído Extra Forte União 500g                       União       Mercearia  Disponivel       25.90  25.90         https://www.mambo.com.br/cafe-torrado-e-moido-extra-forte-uniao-500g/p                         1
24315   Café Torrado e Moído Gourmet Sul de Minas União 250g              União       Mercearia  Disponivel       24.99  24.99         https://www.mambo.com.br/cafe-torrado-e-moido-gourmet-sul-de-minas-uniao-250g/p                1
24316   Café Torrado e Moído Gourmet Cerrado Mineiro União 250g           União       Mercearia  Disponivel       24.99  24.99         https://www.mambo.com.br/cafe-torrado-e-moido-gourmet-cerrado-mineiro-uniao-250g/p             1
24317   Café Torrado e Moído Gourmet Mogiana Paulista União 250g          União       Mercearia  Disponivel       24.99  24.99         https://www.mambo.com.br/cafe-torrado-e-moido-gourmet-mogiana-paulista-uniao-250g/p            1
284608  Cápsula de Café Amaro União 52g com 10 Unidades                   União       Mercearia  Disponivel       16.99  16.99         https://www.mambo.com.br/capsula-de-cafe-amaro-uniao-52g-com-10-unidades/p                     1
284609  Cápsula de Café Ristretto União 52g com 10 Unidades               União       Mercearia  Disponivel       16.99  16.99         https://www.mambo.com.br/capsula-de-cafe-ristretto-uniao-52g-com-10-unidades/p                 1
284610  Cápsula de Café Classico União 52g com 10 Unidades                União       Mercearia  Disponivel       16.99  16.99         https://www.mambo.com.br/capsula-de-cafe-classico-uniao-52g-com-10-unidades/p                  1
284611  Cápsula de Café Velluto União 52g com 10 Unidades                 União       Mercearia  Disponivel       16.99  16.99         https://www.mambo.com.br/capsula-de-cafe-velluto-uniao-52g-com-10-unidades/p                   1
284612  Cápsula de Café Ristretto Descafeinado União 52g com 10 Unidades  União       Mercearia  Disponivel       16.99  16.99         https://www.mambo.com.br/capsula-de-cafe-ristretto-descafeinado-uniao-52g-com-10-unidades/p    1
Name: count, dtype: int64

In [17]:
mambo[mambo["Fabricante"] == "União"].shape[0]

9